mnemonic: "viable ketchup woman library opinion copy rhythm attend rose knock penalty practice photo bundle budget dentist enter round bind holiday useful arch danger lobster"
eth1_premine:
  "m/44'/60'/0'/0/0": 10000000ETH
  "m/44'/60'/0'/0/1": 10000000ETH
  "m/44'/60'/0'/0/2": 10000000ETH
  "m/44'/60'/0'/0/3": 10000000ETH
  "m/44'/60'/0'/0/4": 10000000ETH
  "m/44'/60'/0'/0/5": 10000000ETH
eth1_premine_addrs: {}
chain_id: 1212
deposit_contract_address: "0x1212121212121212121212121212121212121212"
eth1_genesis_timestamp: 0
terminal_total_difficulty: 10000000
mergeForkBlock: 100

clique:
  enabled: false
  signers:
    - 36d56343bc308d4ffaac2f793d121aba905fa6cc
    - 5e762d4a3847cadaf40a4b0c39574b0ff6698c78
    - 15d7acc1019fdf8ab4f0f7bd31ec1487ecb5a2bd
