version: '3.2'

services:
  tx-spammer:
    restart: always
    image: cerc/tx-spammer:local
    env_file:
      - ../config/tx-spammer/tx-spammer.env
    environment:
      ACCOUNTS_CSV_URL: http://fixturenet-eth-bootnode-geth:9898/accounts.csv
      ETH_HTTP_PATH: http://fixturenet-eth-geth-1:8545
      LOG_LEVEL: debug
      SPAMMER_COMMAND: autoSend
    depends_on:
      fixturenet-eth-bootnode-geth:
        condition: service_started
      fixturenet-eth-geth-1:
        condition: service_healthy