version: "3.2"
services:
  ipld-eth-beacon-indexer:
    restart: unless-stopped
    depends_on:
      - ipld-eth-beacon-db
      - lighthouse
    image: vulcanize/ipld-eth-beacon-indexer:local
    volumes:
      - type: bind
        source: ${eth_beacon_config_file}
        target: /root/ipld-eth-beacon-config.json
    environment:
      CAPTURE_MODE: ${eth_beacon_capture_mode}
