name: Fixturenet-Laconicd Test

on:
  push:
    branches: '*'
    paths:
      - '!**'
      - '.github/workflows/triggers/fixturenet-laconicd-test'

jobs:
  test:
    name: "Run fixturenet-laconicd test suite"
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup jq'
        run: apt-get install jq -y
      - name: 'Check jq'
        run: |
          which jq
          jq --version 
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: "Print Python version"
        run: python3 --version
      - name: "Install shiv"
        run: pip install shiv
      - name: "Generate build version file"
        run: ./scripts/create_build_tag_file.sh
      - name: "Build local shiv package"
        run: ./scripts/build_shiv_package.sh
      - name: "Run fixturenet-laconicd tests"
        run: ./tests/fixturenet-laconicd/run-test.sh
