name: Fixturenet-Payments Test

on:
  pull_request:
    branches: '*'
  push:
    branches: '*'

jobs:
  test:
    name: "Run basic test suite"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: "Print Python version"
        run: python3 --version
      - name: "Install shiv"
        run: pip install shiv
      - name: "Generate build version file"
        run: ./scripts/create_build_tag_file.sh
      - name: "Build local shiv package"
        run: ./scripts/build_shiv_package.sh
      - name: "Run fixturenet-payments tests"
        run: ./tests/fixturenet-payments/run-test.sh